# Generated by Django 5.1.3 on 2024-11-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="telegram_tag",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
