# Generated by Django 5.1.3 on 2024-11-27 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_userprofile_telegram_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="is_online",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="link",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="telegram_tag",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_registration",
                        message="Enter a valid registration number in the format @ExampleTag.",
                        regex="^@\\w{5,}$",
                    )
                ],
            ),
        ),
    ]
