# Generated by Django 5.1.3 on 2024-11-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_meeting_is_online_meeting_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="telegram_tag",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="teams_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tg_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_description",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
    ]
