# Generated by Django 5.1.3 on 2026-02-12 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_meeting_notified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="notified",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="teams_id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="tg_id",
        ),
    ]
