# Generated by Django 5.1.3 on 2026-02-12 10:58

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_remove_meeting_notified_remove_userprofile_teams_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="Tag")),
                ("slug", models.SlugField(blank=True, max_length=60, unique=True)),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#FF0000",
                        image_field=None,
                        max_length=25,
                        samples=[
                            "#FF0000",
                            "#0000FF",
                            "#00FF00",
                            "#FFFF00",
                            "#FFA500",
                            "#800080",
                            "#FFC0CB",
                            "#00FFFF",
                            "#8B4513",
                            "#808080",
                            "#00008B",
                            "#006400",
                            "#800000",
                            "#808000",
                            "#40E0D0",
                        ],
                        verbose_name="Tag color",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="meeting",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="meetings", to="api.tag"),
        ),
    ]
