# Generated by Django 5.2.11 on 2026-02-13 09:55

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_tag_meeting_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="duration",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FF0000",
                image_field=None,
                max_length=25,
                samples=[
                    ("#FF0000", "Red"),
                    ("#0000FF", "Blue"),
                    ("#00FF00", "Green"),
                    ("#FFFF00", "Yellow"),
                    ("#FFA500", "Orange"),
                    ("#800080", "Purple"),
                    ("#FFC0CB", "Pink"),
                    ("#00FFFF", "Cyan"),
                    ("#8B4513", "Brown"),
                    ("#808080", "Gray"),
                    ("#00008B", "Dark Blue"),
                    ("#006400", "Dark Green"),
                    ("#800000", "Maroon"),
                    ("#808000", "Olive"),
                    ("#40E0D0", "Turquoise"),
                ],
                verbose_name="Tag color",
            ),
        ),
    ]
