# Generated by Django 5.2.11 on 2026-05-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_meeting_duration_alter_tag_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="description",
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="link",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="location",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
